# Generated by Django 3.2.3 on 2021-05-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0003_auto_20210519_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyRegister',
        ),
    ]
