# Generated by Django 3.2.3 on 2021-05-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0005_verifyemaillinkcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('p_id_pk', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('user_id_fk', models.IntegerField()),
                ('p_desc', models.CharField(max_length=250)),
                ('p_price', models.CharField(max_length=10)),
                ('p_image', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
    ]
